akhq:
  connections:
    kafka-kraft-cluster:
      properties:
        bootstrap.servers: "broker1:9096,broker2:9096,broker3:9096"
        security.protocol: SSL
        ssl.truststore.location: /certs/jks/akhq/truststore.p12
        ssl.truststore.type: PKCS12
        ssl.truststore.password: changeit-dev-only
        ssl.keystore.location: /certs/jks/akhq/keystore.p12
        ssl.keystore.type: PKCS12
        ssl.keystore.password: changeit-dev-only
        ssl.key.password: changeit-dev-only
        ssl.endpoint.identification.algorithm: https
      jmx:
        - name: broker1
          url: "broker1:9101"
        - name: broker2
          url: "broker2:9101"
        - name: broker3
          url: "broker3:9101"
      connect:
        - name: "kafka-connect"
          url: "http://kafka-connect:8083"
      schema-registry:
        url: "http://schema-registry:8081"
        basic-auth:
          username: "${SCHEMA_REGISTRY_ADMIN_USER:admin}"
          password: "${SCHEMA_REGISTRY_ADMIN_PASSWORD:change-me-in-real-deployments}"
