apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      tlsAuth: false
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: "$__file{/certs/ca/ca-bundle.pem}"

  - name: Loki
    type: loki
    access: proxy
    url: https://loki:3100
    uid: loki
    editable: true
    jsonData:
      tlsAuthWithCACert: true
      derivedFields:
        - name: TraceID
          matcherRegex: "traceID=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo
    secureJsonData:
      tlsCACert: "$__file{/certs/ca/ca-bundle.pem}"

  - name: Tempo
    type: tempo
    access: proxy
    url: https://tempo:3200
    editable: true
    uid: tempo
    jsonData:
      tlsAuthWithCACert: true
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    secureJsonData:
      tlsCACert: "$__file{/certs/ca/ca-bundle.pem}"

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    uid: pyroscope
    editable: true
    jsonData:
      minStep: "15s"
