global:
  resolve_timeout: 5m

route:
  group_by: ['cluster', 'alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: ntfy-kafka

receivers:
  - name: ntfy-kafka
    webhook_configs:
      - url: 'http://ntfy/kafka-alerts-c3f8a2d1'
        send_resolved: true
        http_config:
          follow_redirects: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['cluster', 'alertname']
