logger:
  level: info

kafka:
  brokers:
    - broker1:9095
    - broker2:9095
    - broker3:9095
  clientId: kminion
  tls:
    enabled: false
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    username: kminion
    password: ${SCRAM_KMINION_PASSWORD}

minion:
  consumerGroups:
    enabled: true
    scrapeMode: adminApi
    granularity: partition
    allowedGroups: [".*"]
    ignoredGroups: []
  topics:
    granularity: partition
    allowedTopics: [".*"]
    ignoredTopics: []
  logDirs:
    enabled: true
  endToEnd:
    enabled: false

exporter:
  namespace: kminion
  host: 0.0.0.0
  port: 8080
