logger:
  level: info

kafka:
  brokers:
    - broker1:9092
    - broker2:9092
    - broker3:9092
  clientId: kminion
  tls:
    enabled: false
  sasl:
    enabled: false

minion:
  consumerGroups:
    enabled: true
    scrapeMode: adminApi
    granularity: partition
    allowedGroups: [".*"]
    ignoredGroups: []
  topics:
    granularity: partition
    allowedTopics: [".*"]
    ignoredTopics: []
  logDirs:
    enabled: true
  endToEnd:
    enabled: false

exporter:
  namespace: kminion
  host: 0.0.0.0
  port: 8080
