logger:
  level: info

kafka:
  brokers:
    - broker1:9096
    - broker2:9096
    - broker3:9096
  clientId: kminion
  tls:
    enabled: true
    caFilepath: /certs/ca/ca-bundle.pem
    certFilepath: /certs/pem/kminion/tls.crt
    keyFilepath: /certs/pem/kminion/tls.key

minion:
  consumerGroups:
    enabled: true
    scrapeMode: adminApi
    granularity: partition
    allowedGroups: [".*"]
    ignoredGroups: []
  topics:
    granularity: partition
    allowedTopics: [".*"]
    ignoredTopics: []
  logDirs:
    enabled: true
  endToEnd:
    enabled: false

exporter:
  namespace: kminion
  host: 0.0.0.0
  port: 8080
